### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-intermedia-conchaasensiomr#1]
Muy buen trabajo @conchaasensiomr!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 300 / 347
- [x] HTML > LINK: Debemos tener dos ficheros de estilos importados con un `link`.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > COLOR: El color de los enlaces debe ser  4a4a4a
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > FLEX: El texto Creando diversidad digital debe estar centrado horizontal y verticalmente, lo mejor es hacerlo con flex.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by conchaasensio** [comment]
¡Hola, Miguel! Gracias por las sugerencias. Ya están corregidas :)

No obstante, como ya comentamos el otro día, hay algunas que estaban hechas desde el principio, así que lo he dejado igual.

Cualquier cosa, me decís.

¡Saludos!

**Comment by migueldelmazo** [comment]
Perfecto, gracias por avisar!!!
